apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssh.fullname" . }}
  labels:
    {{- include "ssh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2222
      protocol: TCP
      name: ssh
  selector:
    {{- include "ssh.selectorLabels" . | nindent 4 }}
