apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "connectbox-exporter.name" . }}-config
data:
  config.yml: |
    # Connect Box IP address
    ip_address: {{ .Values.config.ipAddress }}

    # Connect Box web interface password
    password: {{ .Values.config.password }}

    # All following parameters are optional.
    exporter:
        # port on which this exporter exposes metrics (default: 9705)
        port: {{ .Values.service.port }}

        # timeout duration for connections to the Connect Box (default: 9)
        timeout_seconds: {{ .Values.config.timeoutSeconds }}

        # Customize the family of metrics to scrape. By default, all metrics are scraped.
        #metrics: [device_status, downstream, upstream, lan_users, temperature]
