{{- if .Values.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: service-prometheus
    role: alert-rules
  name: {{ include "connectbox-exporter.fullname" . }}
spec:
  groups:
  - name: connectbox-exporter.rules
    rules:
{{ .Files.Get "files/prometheus.rules" }}
{{- end }}
