apiVersion: v1
kind: Service
metadata:
  name: {{ include "connectbox-exporter.name" . }}
  labels:
    {{- include "connectbox-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "connectbox-exporter.selectorLabels" . | nindent 4 }}
