{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ecowitt-exporter.fullname" . }}
  labels:
    {{- include "ecowitt-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ecowitt-exporter.labels" . | nindent 6 }}
  endpoints:
  - port: http
    interval: 60s
    relabelings:
      - action: labeldrop
        regex: pod
        sourceLabels: []
      - action: labeldrop
        regex: namespace
        sourceLabels: []
      - action: labeldrop
        regex: instance
        sourceLabels: []
      - action: labeldrop
        regex: job
        sourceLabels: []
{{- end }}
