image:
  repository: linuxserver/ddclient
  pullPolicy: IfNotPresent
  tag:

strategy:
  type: Recreate

env: {}
  # TZ:
  # PUID:
  # PGID:

service:
  enabled: false

ingress:
  enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    type: configMap
    mountPath: /defaults/ddclient.conf
    subPath: ddclient.conf

configmap:
  config:
    # -- Store ddclient configuration as a ConfigMap
    enabled: true
    data:
      ddclient.conf: |
        # This is the configuration for ddclient
        # Inorder for it to function you need to set it up
        # e.g. this is the config for Cloudflare
        daemon=600
        use=web
        web=dynamicdns.park-your-domain.com/getip
        protocol=cloudflare
        ssl=yes
        ttl=1
        login=${CF_EMAIL}
        password=${CF_GLOBAL_APIKEY}
        zone=${DOMAIN}.${TLD}
        ${DOMAIN}.${TLD}
