apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-settings
  labels:
    {{- include "ddclient.labels" . | nindent 4 }}
data:
  ddclient.conf: |
{{ .Values.config | indent 4 }}
